# Generated by Django 2.1.7 on 2025-08-04 11:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Tshirt', 'T-shirt'), ('Shirt', 'Shirt'), ('Jeans', 'Jeans'), ('Hoodie', 'Hoodie'), ('Dress', 'Dress'), ('Skirt', 'Skirt')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_sizes', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('color', models.CharField(max_length=30)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
