# Generated by Django 4.2.18 on 2026-01-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together={('product', 'type_name')},
        ),
    ]
