# Generated by Django 5.1.4 on 2025-08-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='producttype',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
