# Generated by Django 4.2.18 on 2026-01-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_producttype_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together=set(),
        ),
    ]
