# Generated by Django 2.1.7 on 2025-08-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_auto_20250804_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='P001', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
