# Generated by Django 5.1.4 on 2025-08-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_remove_producttype_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
