# Generated by Django 2.1.7 on 2025-08-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_auto_20250804_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
