# Generated by Django 5.1.4 on 2025-09-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_producttype_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorsize',
            name='size',
            field=models.CharField(choices=[('XXS', 'Extra Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('XXXL', 'Extra Extra Extra Large')], max_length=5),
        ),
    ]
