# Generated by Django 5.2.6 on 2025-10-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_productcolorsize_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdesign',
            name='show_in_shop',
            field=models.BooleanField(default=False),
        ),
    ]
