# Generated by Django 2.1.7 on 2025-08-04 12:58

import Services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_auto_20250804_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=Services.models.ProductImagePath()),
        ),
    ]
