# Generated by Django 2.1.7 on 2025-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_auto_20250804_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tshirt', 'T-shirt'), ('Acid Wash T-Shirt', 'Acid Wash T-Shirt'), ('Hoodie', 'Hoodie')], max_length=50),
        ),
    ]
