# Generated by Django 2.1.7 on 2025-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_auto_20250804_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
