# Generated by Django 3.2.25 on 2025-08-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_alter_productsize_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_l',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_m',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_xl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_xs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_xxl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_xxs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_xxxl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
