# Generated by Django 5.1.4 on 2025-08-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
