# Generated by Django 5.1.4 on 2025-08-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0013_remove_product_image_productimage_is_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_cover',
        ),
    ]
