# Generated by Django 5.1.4 on 2025-08-30 21:03

import Services.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0014_remove_productimage_is_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_m',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_s',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_xl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_xs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_xxl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_xxs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_xxxl',
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Services.models.ProductImagePath())),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='Services.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XXS', 'XX-Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2XL'), ('XXXL', '3XL')], max_length=5)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='Services.productcolor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Services.models.ProductImagePath())),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='Services.productcolor')),
            ],
        ),
    ]
