# Generated by Django 5.1.4 on 2025-08-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0016_productimage_color_productimage_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='image',
        ),
    ]
