# Generated by Django 5.1.4 on 2025-08-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0017_remove_productcolor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdesign',
            name='image',
        ),
    ]
