# Generated by Django 5.1.4 on 2025-08-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0018_remove_productdesign_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='productdesign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
