# Generated by Django 5.1.4 on 2025-08-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0019_remove_product_description_productdesign_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
