# Generated by Django 5.1.4 on 2025-08-31 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0023_remove_product_discount_percent_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdesign',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='Services.producttype'),
        ),
    ]
