# Generated by Django 4.2.18 on 2026-01-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phonepe_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_order_id',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
