# Generated by Django 5.1.4 on 2025-08-31 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Services', '0003_alter_producttype_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Services.productdesign'),
        ),
    ]
