# Generated by Django 4.2.18 on 2026-01-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_design_options'),
        ('Accounts', '0002_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='profile',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'design')},
        ),
    ]
