# Generated by Django 4.2.18 on 2026-01-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_payment_phonepe_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='INITIATED', max_length=20),
        ),
    ]
