# Generated by Django 3.2.25 on 2025-08-23 12:48

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_order_orderitem_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.profile_picture_upload_path),
        ),
    ]
