# Generated by Django 5.1.4 on 2025-09-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_order_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
