# Generated by Django 3.2.25 on 2025-08-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
