# Generated by Django 4.2.18 on 2026-01-22 16:46

import cloudinary.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='Default Design Name', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('show_in_shop', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='Products.product')),
            ],
            options={
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('plain', 'Plain'), ('printed', 'Printed'), ('embroidery', 'Embroidery')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='Products.product')),
            ],
            options={
                'unique_together': {('product', 'type_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_primary', models.BooleanField(default=False)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Products.design')),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='Products.productcolor'),
        ),
        migrations.AddField(
            model_name='design',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='Products.product'),
        ),
        migrations.AddField(
            model_name='design',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='Products.producttype'),
        ),
        migrations.CreateModel(
            name='ProductColorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=5)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='Products.productcolor')),
            ],
            options={
                'indexes': [models.Index(fields=['color', 'size'], name='Products_pr_color_i_52fe57_idx')],
                'unique_together': {('color', 'size')},
            },
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['product', 'product_type', 'color'], name='Products_de_product_eb2838_idx'),
        ),
    ]
