# Generated by Django 4.2.18 on 2026-01-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='design',
            unique_together=set(),
        ),
    ]
