# Generated by Django 4.2.18 on 2026-01-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_design_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['product', 'product_type', 'color'], name='Products_de_product_eb2838_idx'),
        ),
    ]
