# Generated by Django 4.2.18 on 2026-01-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_producttype_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='show_in_shop',
            field=models.BooleanField(default=True),
        ),
    ]
