# Generated by Django 4.2.18 on 2026-01-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_productimage_show_in_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
