# Generated by Django 4.2.18 on 2026-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_design_products_de_product_eb2838_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
