# Generated by Django 4.2.18 on 2026-01-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_design_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['position', '-id']},
        ),
    ]
